
services:
  chroma:
    image: chromadb/chroma:latest
    restart: always
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=*
      - ANONYMIZED_TELEMETRY=False
    ports:
      - '8002:8000'
    volumes:
      - chroma_data:/chroma/.chroma/index

  ingestion-api:
    build:
      context: ./ingestion-api
    restart: always
    ports:
      - "8001:8008"
    volumes:
      - ./ingestion-api:/app
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8008 --reload
    depends_on:
      - chroma

volumes:
  chroma_data: